#!/usr/bin/env ruby

# from http://errtheblog.com/posts/89-huba-huba

home = File.expand_path('~')

Dir.glob('*', File::FNM_DOTMATCH).each do |file|
  next if %w(. .. install .git .gitmodules).include?(file) || file =~ /.swp$/

  target = File.join(home, "#{file}")

  if File.exists? target
    puts " !! #{target} already exists"
  else
    `ln -s #{File.expand_path file} #{target}`
    puts " -> linked #{file} to #{target}"
  end
end

