#!/usr/bin/env ruby

desc "Create symlinks to config files in home directory"
task :install do |t|
  files_to_ignore = %w(
    .
    ..
    .git
    .gitignore
    .gitmodules
    rakefile
    README.md)

  home = File.expand_path('~')

  Dir.glob('*', File::FNM_DOTMATCH).each do |file|
    next if files_to_ignore.include?(file) || file =~ /.swp$/

    target = File.join(home, "#{file}")

    if File.exists? target
      puts " !! #{target} already exists"
    else
      `ln -s #{File.expand_path file} #{target}`
      puts " -> linked #{file} to #{target}"
    end
  end
end
