#!/usr/bin/env ruby

desc "Create symlinks to config files in home directory"
task :install do |t|
  files_to_ignore = %w(
    .
    ..
    .git
    .gitmodules
    rakefile
    README.md)

  home = File.expand_path('~')

  Dir.glob('*', File::FNM_DOTMATCH).each do |file|
    next if files_to_ignore.include?(file) || file =~ /.swp$/

    target = File.join(home, "#{file}")

    if File.exists? target
      puts " !! #{target} already exists"
    else
      `ln -s #{File.expand_path file} #{target}`
      puts " -> linked #{file} to #{target}"
    end
  end
end

namespace :vim do
  desc "Update Vim plugins registered as submodules"
  task :update_plugins do |t|
    sh "git submodule foreach 'git pull origin master'"
  end

  desc "Install VIM plugin from clipboard"
  task :add_plugin do |t|
    repo = `pbpaste`
    name = repo.split("/").last.gsub(".git","")
    sh "git submodule add #{repo} .vim/bundle/#{name}"
  end
end
